locations:
  home:
    waypoints:
      - {x: 0.0, y: 0.0}

  room_1:
    waypoints:
      - {x: -2.5, y: 0.0}   # Drive down left corridor
      - {x: -5.0, y: 5.0}   # Turn into Room 1

  room_2:
    waypoints:
      - {x: 0.0, y: 2.5}    # Drive up central corridor
      - {x: 0.5, y: 5.0}    # Turn into Room 2

  room_3:
    waypoints:
      - {x: 2.5, y: 0.0}    # Drive down right corridor
      - {x: 5.0, y: -5.0}   # Turn through doorway into Room 3